// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :exec
delete from chirps where id = $1
`

func (q *Queries) DeleteChirp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, id)
	return err
}

const getChirp = `-- name: GetChirp :one
select id, created_at, updated_at, body, user_id from chirps where id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const retrieveAllChirps_Asc = `-- name: RetrieveAllChirps_Asc :many
select id, created_at, updated_at, body, user_id from chirps order by created_at asc
`

func (q *Queries) RetrieveAllChirps_Asc(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, retrieveAllChirps_Asc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveAllChirps_Desc = `-- name: RetrieveAllChirps_Desc :many
select id, created_at, updated_at, body, user_id from chirps order by created_at desc
`

func (q *Queries) RetrieveAllChirps_Desc(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, retrieveAllChirps_Desc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveChirpsByAuthorID_Asc = `-- name: RetrieveChirpsByAuthorID_Asc :many
select id, created_at, updated_at, body, user_id from chirps where user_id = $1 order by created_at asc
`

func (q *Queries) RetrieveChirpsByAuthorID_Asc(ctx context.Context, userID uuid.UUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, retrieveChirpsByAuthorID_Asc, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveChirpsByAuthorID_Desc = `-- name: RetrieveChirpsByAuthorID_Desc :many
select id, created_at, updated_at, body, user_id from chirps where user_id = $1 order by created_at desc
`

func (q *Queries) RetrieveChirpsByAuthorID_Desc(ctx context.Context, userID uuid.UUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, retrieveChirpsByAuthorID_Desc, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveChirp = `-- name: SaveChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type SaveChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) SaveChirp(ctx context.Context, arg SaveChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, saveChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
